version: "3.9"
services:
  klarity:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - KD_AUTH_MODE=none
      - KD_LOG_LEVEL=info
      - KD_LOG_FORMAT=text
      - KD_SERVER_METRICSENABLED=true
    volumes:
      - ${KUBECONFIG:-~/.kube/config}:/home/dashboard/.kube/config:ro
      - ~/.aws:/home/dashboard/.aws:ro # aws config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
